### ISSUE TITLE
Support to CancellationToken

### ISSUE THREAD

**Issue by danielmitre** [0x1000000/SqExpress#3]
I'm testing some ideas with this library but I'm having difficulties cancelling running queries. Do you have any plans of adding an `async` versions of the query methods with support to CancellationToken?

I didn't look into many implementations, but `System.Data.Odbc.OdbcCommand` have async methods with support to `CancellationToken`, so I created a custom `DbCommand` to make the **async** calls in a synchronous way in the synchronous methods.

And it indeed works, but is far from ideal because it makes the error stack a lot less helpful and the cancellationToken is now bound to the DbCommand entirely.

Thank you for the library, keep you with the good work.

**Comment by 0x1000000** [comment]
Thank you for the feedback! I will try to solve the problem in a next release

**Comment by 0x1000000** [comment]
The feature was added in v0.3.2
